### ISSUE TITLE
Algolia search does not work anymore

### ISSUE THREAD

**Issue by MockingMagician** [doctrine/doctrine-website#424] opened 2021-11-15 10:23 UTC
Hi,

It looks like the algolia search engine always return not found result for any searched terms. But for sure, it should be.

Search done from URI : https://www.doctrine-project.org/projects/doctrine-mongodb-odm/en/2.2/

![Capture d’écran de 2021-11-15 11-14-30](https://user-images.githubusercontent.com/33423809/141765109-77c0e39f-e615-43b0-9515-b56aaf85dc87.png)

![Capture d’écran de 2021-11-15 11-14-42](https://user-images.githubusercontent.com/33423809/141765103-0faf73bc-9e75-4afe-8868-71dddc53e77d.png)

**Comment by kevin-rv** [comment] 2021-11-24 11:04
Hi,  I have the same problem when it will be solved ?

**Comment by greg0ire** [comment] 2021-11-24 19:17
Seems related to #417

**Comment by SenseException** [comment] 2021-11-24 22:26
It depends on new branches of projects. When a new branch or version gets released, the search index for that version doesn't exist yet. It currently needs to be created manually. There's also a change when the previous `latest` version gets replaced by a new one and won't have an available version-fit index.

I've created the search-index for mongodb-odm 2.2 now and it should work.

**Comment by MockingMagician** [comment] 2021-11-25 08:18
Hi @greg0ire , @SenseException 

Thanks for all, but it still not work.

**Comment by SenseException** [comment] 2021-11-25 20:22
This time we have reached the limit for the month. The search of the other docs aren't working anymore too. This is something I cannot fix :disappointed:

**Comment by MockingMagician** [comment] 2021-11-26 12:12
@SenseException Gosh!

It is hudge problem here, cause most part of the doc is not accessible from doc menu. It is possible to help you in any way ?

**Comment by greg0ire** [comment] 2021-11-26 13:02
You can contribute something to https://github.com/doctrine/mongodb-odm/blob/2.2.x/docs/en/sidebar.rst if it's missing

**Comment by malarzm** [comment] 2021-11-26 18:09
@greg0ire I believe the problem is that we do have those in the sidebar, but they're not visible: https://github.com/doctrine/mongodb-odm/issues/2099. Maybe it'll be easier to debug the issue now the build process is on Github?

**Comment by SenseException** [comment] 2021-12-01 23:15
Different issue. As @malarzm already mentioned are the missing sidebar links part of doctrine/mongodb-odm#2099. I've put a comment into the issue about a possible reason for the missing links, but the source of it needs to be found. Please use the issue there for the doc menu problems. I assume other Doctrine projects might also have this problem.

**Comment by SenseException** [comment] 2023-11-03 19:38
The search index will be [updated for all projects once a month](https://github.com/doctrine/doctrine-website/blob/master/.github/workflows/search-index.yml). This will make sure that the index will get the latest changes to the docs and that new versions won't stay empty for too long.

When new versions of a project are created (aka new version branch), then the docs do exist and are build on the next Website deployment. The Algolia index isn't created with it which is why sometimes there are versions without search results. Tags like "current" or "latest" will link to different versions once change happens, but the index will still have them linked to the previous assigned versions before the Website build.

The indexing surely can be improved, but for now I'll close this issue as the basic problem of "no indices created ever" was solved. More can be read in #417 and #520.

**Closed by SenseException** 2023-11-03 19:38 UTC
