### ISSUE TITLE
Deprecation summary

### ISSUE THREAD

**Issue by jwage** [doctrine/doctrine-website#200] opened 2018-08-10 13:58 UTC
The point of this GitHub issue is to discuss in a more organized way the different ways we can handle deprecations in Doctrine.

The policy of Doctrine for a very long time has been to use `@deprecated` and only very recently did we start to introduce usages of `@trigger_error` which has led to this discussion of how they should be used and in which use cases.

## Using `trigger_error()` with `@` and `phpunit-bridge`.

- It is always called in production.
- Causes bug reports to us that aren't bugs and we have to explain it is a deprecation error and they should handle it properly in their build with something like phpunit bridge.
- People who don't use `phpunit-bridge` would have to depend on the CHANGELOG to know what has changed.
- It won't report to you calls to deprecated code if your test suite does not execute that code path or the code that is calling the deprecated code is dead.
- `phpunit-bridge` reports deprecated method calls that your project indirectly calls. See 3 and 4 in this comment https://github.com/doctrine/common/pull/849#issuecomment-407053196

## Using `@deprecated` and `phpstan-deprecation-rules`.

- Means other major dependents won't be automatically notified about deprecations if they aren't using `phpstan-deprecation-rules`.
- It seems like the `phpunit-bridge` can handle SOME `@deprecated` scenarios, but it is not clear to me the extent of this functionality.
- If we immediately switch to this, any dependents of Doctrine won't be automatically notified of deprecations if they aren't using `phpstan-deprecation-rules`. However, this is the same as if we are using `@trigger_error` and someone isn't using phpunit-bridge.
- People who don't use `phpstan-deprecation-rules` would have to depend on the CHANGELOG to know what has changed.
- `phpstan-deprecation-rules` will tell you when you call something that is deprecated, even if your test suite doesn't execute the code or the code is dead. `phpstan` will also notify you of the dead code that could be removed which gets rid of the call to the deprecated code.
- What happens in the scenario when a Doctrine column type that’s deprecated is referenced in XML?
  - @lcobucci is chatting with phpstan folks to see if things can be improved to handle the above two "problems"
- What happens if a users project uses Twig and they call a Twig function that calls something deprecated in Doctrine?
  - PHPStan will see that you have a method that is calling a deprecated method. Even if that parent method is never called in your test suite/build process.
- What happens when you have a conditional deprecation? How does this work with `phpstan-deprecation-rules`? e.g.
  - Here we would use `trigger_error()` without the `@` and suggest to people to appropriately configure PHP with `error_reporting()`

```php
<?php

if ($featureFlag) {
    @trigger_error(E_USER_DEPRECATED, 'This is deprecated');
}
```

## Pslam

Another tool that can statically analyze your code and show you deprecated code that you are relying on. https://getpsalm.org/

## `phpunit-bridge` default behavior

```php
<?php

// Symfony
class SomeSymfonyClass
{
    private $em;

    public function __construct(EntityManager $em)
    {
        $this->em = $em;
    }

    public function doSomething()
    {
        $this->em->notDeprecatedMethod();
    }
}

// Doctrine
class EntityManager
{
    public function notDeprecatedMethod()
    {
        $this->deprecatedMethod();
    }

    public function deprecatedMethod()
    {
        trigger_error(E_USER_DEPRECATED, 'This is deprecated');
    }
}

$someSymfonyClass = new SomeSymfonyClass();
$someSymfonyClass->doSomething();
```

Right now `phpunit-bridge` would report `deprecatedMethod()` but it was indirectly called.
Symfony can't control or fix this fact. It is up to Doctrine internals to decide when to stop calling `deprecatedMethod`. As long as Symfony is not calling methods directly that are deprecated, they should not care.

It is helpful to get these indirect deprecated dependencies as a report, but I don't believe it should cause a hard failure in the test suite.

### Use Both

Use `@deprecated` + `phpstan-deprecation-rules` and `trigger_error()` at the same time. This way our deprecations get reported no matter if the user is using both `phpstan-deprecation-rules` and `phpunit-bridge` or just one of them.

Both tools will find this:

```
/** @deprecated */
function foo() : void {
  @trigger_error('bla', E_USER_DEPRECATED);
}
foo();
```

### Use One or the Other

Use `@deprecated` + `phpstan-deprecation-rules` in a majority of the use cases where possible. When we have conditional deprecations, use `trigger_error()` without the `@`.

This approach requires that a project/library that depends on us must have `phpstan-deprecation-rules` in their project. Otherwise they will miss out on deprecations that don't use `trigger_error()`.

This approach requires that a project/library that depends on us must have `phpunit-bridge` installed or they setup their own custom error handler in order to be notified of deprecations that are handled with `trigger_error()`

PHPStan will find this deprecation. PHPUnit bridge won't:

```
/** @deprecated */
function foo() : void {}
foo();
```

PHPUnit bridge will find this deprecation. PHPStan won't:

```
function foo() : void {
  @trigger_error('bla', E_USER_DEPRECATED);
}
foo();
```

### Enhance PHPStan

Ideally we'd be able to enhance PHPStan to support everything we need in order to stop using `trigger_error()` entirely. This depends on the technical enhancements of PHPStan, but it also means we need to get other projects and end users to adopt `phpstan-deprecation-rules`.

If a project doesn't use `phpstan-deprecation-rules` and we only use the phpstan way, then projects like Symfony and other end user projects that only use `phpunit-bridge` will not be notified of our deprecations.

**Comment by Ocramius** [comment] 2018-08-10 14:07
Overall, I think `@deprecated` checking is easily detected at build/installation time by analyzing any first-level access to `@deprecated` endpoints.

For example, if a third party dependency of the ORM uses a deprecated API in its internals, we are out of control when it comes to fixing that deprecation usage, and the author of that library has no control or time to fix it quickly: this makes deprecations much bigger and problematic than they actually are.

The same applies to consumers of our packages: if they use doctrine's APIs through other libraries (which is very, very likely!), they may run into one of these deprecations, and forcing them to run tests with a tool that ignores deprecations is not right either.

The choice of when to fix a deprecation should be on the consumer of the library, so we can make it as noisy as possible, but not stop their deployment processes, because that's still a BC break.

Therefore I'd say let's reverse the `@trigger_error()` and go with `@deprecated` for now, and suggest to users how to make sure that they don't use deprecated API instead (I think that pointing them to the PHPStan deprecation rules is OK).

**Comment by lcobucci** [comment] 2018-08-10 16:12
> What happens in the scenario when a Doctrine column type that’s deprecated is referenced in XML?

After chatting with @ondrejmirtes, we've agreed that the best solution would be proving a better integration in `phpstan/phpstan-doctrine` with the `EntityManager` for people using the ORM and the `DocumentManager` for people using the ODM. This will allow us to provide a better integration between PHPstan and the ORM/ODM, like knowing the type of the columns and what class is used as the repository of an entity..

That implementation was started by @malarzm https://github.com/phpstan/phpstan-doctrine/pull/18 and I'll try to finish it on the upcoming days.

> What happens if a users project uses Twig and they call a Twig function that calls something deprecated in Doctrine?

This is rather out of scope since I shouldn't be bothered if the dependencies I'm using are calling deprecated things.

**Comment by ostrolucky** [comment] 2018-08-11 12:29
I want to ask what problem are we trying to solve here? Then it will be more clear what needs to be changed in order to solve it. This is very important.

___

> Therefore I'd say let's reverse the @trigger_error() and go with `@deprecated` for now, and suggest to users how to make sure that they don't use deprecated API instead (I think that pointing them to the PHPStan deprecation rules is OK).

Have you read following?

> When we have conditional deprecations, we can use trigger_error() without the @

We can't drop it completely, unless we solve such deprecations by nuking whole class/method and replacing it with new one, which is not very realistic. [Some](https://github.com/doctrine/dbal/blob/66daecd0084118ec04c54288915a8eb9bac7511d/lib/Doctrine/DBAL/Driver/PDOStatement.php#L221) [examples](https://github.com/doctrine/cache/blob/5e65fc393ecc17e395ac44d7b855dcf5e6864f34/lib/Doctrine/Common/Cache/MongoDBCache.php#L54)


> The choice of when to fix a deprecation should be on the consumer of the library, so we can make it as noisy as possible, but not stop their deployment processes, because that's still a BC break.

Following this, we can't turn `@trigger_error` into `trigger_error`

**Comment by Ocramius** [comment] 2018-08-11 12:30
The idea would to be removing `trigger_error()` completely, and use only `@deprecated`.

**Comment by jwage** [comment] 2018-08-11 14:15
@ostrolucky We are trying to create and support a designed solution for handling deprecations that does not rely on the runtime of your test suite, clicking around in your application and does not depend on the use of `@`.

Right now, in a majority of cases, `@deprecated` works. We will try to do it this way and avoid conditional deprecations, but if we cannot find a way or it is absolutely too difficult, `trigger_error()` is acceptable.

> Following this, we can't turn `@trigger_error` into `trigger_error`

I think we can, people can and should configure their error reporting properly to either ignore or report `E_USER_DEPRECATED`. In their test suite, they would silence `E_USER_DEPRECATED` and use `phpunit-bridge` or a custom error handler to decide what to do with these deprecation errors. Our preference is that only deprecation errors you directly invoke, cause your build to fail. Deprecations you indirectly trigger should be ignored or reported to you, but should not cause the build to fail.

**Comment by ostrolucky** [comment] 2018-08-11 14:46
> We are trying to create and support a designed solution for handling deprecations that does not rely on the runtime of your test suite, clicking around in your application and does not depend on the use of @.

Having both `@deprecated` and `trigger_error` has advantages of both static analysis and runtime handler. This is rationally the way to go if you just want widest coverage of deprecation detection. And it's already done e.g in DoctrineBundle. Why is goal of this issue dropping runtime based deprecation mechanism, instead of expanding ways how users can detect deprecations? Furthermore, I don't see why would static analysis be limited in detecting `@deprecated` and not support `trigger_error`. There is no technical limitation of that, AFAIK it's just something missing from current analyzers.

We swap one thing with limitations with another thing with other limitations, instead of combining powers of both of them. I think everybody here realizes static analysis in its current state completely fails for any dynamic usage of deprecated code. I'm going to use painfully simple obvious example `new $_GET['foo']()`. There is no way any static analysis solution would catch that, but runtime solution will. Less painful examples are XML/YAML configuration of mapping and DIC. Same for twig extensions in where PHP code is in vendor. Why would we take away ability to detect these?

> people can and should configure

Like @Ocramius says, requiring people to do this just because they upgraded minor version might be considered breaking change.

>The idea would to be removing trigger_error() completely, and use only @deprecated.

Can you reply to other points of my points too? Just paragraph above the one you are replying to I cite why trigger_error can't be completely dropped. I did not see any suggested alternatives for conditional deprecations.

**Comment by jwage** [comment] 2018-08-11 15:31
@ostrolucky The language I used in my comment was the following:

> Right now, in a majority of cases, @deprecated works. We will try to do it this way and avoid conditional deprecations, but if we cannot find a way or it is absolutely too difficult, trigger_error() is acceptable.

We would still use `trigger_error()` in the cases where we can't figure out how to make `@deprecated` work by refactoring or it is too difficult to do.

**Comment by rzilin** [comment] 2018-08-12 14:36
using `trigger_error` does not make sense deprecation is not error and force people to configure php.ini to hide does not have reasonable point. Someone decided to use and now everyone should change apps configuration just because someone things it is good thing.

I would say who supports trigger_error  they should first ask php team to implement to disable it by default so that will avoid causing issues in production servers

**Comment by nicolas-grekas** [comment] 2018-08-13 08:09
Hello, it would be great to move this discussion to the FIG.
We have plenty of experience on the topic with Symfony, and I'm a bit disappointed all the work that happened there already did percolate here. The case is strong IMHO for keeping the silenced deprecations notices at runtime. Completing it with static analysis would be awesome, that's always been a missing part.
But discussing this in yet another issue won't help much move forward, except Doctrine of course: maybe Doctrine will borrow some bits from the previous experience, but other projects would still have to reinvent the wheel when wondering again the same in the future. Also, creating a different policy than Symfony on this one would degrade the overall experience of Symfony devs because they would have to deal with two ways of dealing with deprecations.
I'd like a goal of this discussion could be to create a *common* policy for at least Symfony + Doctrine (+ all others that already follow Symfony's policy, e.g. Drupal.)

**Comment by lcobucci** [comment] 2018-08-13 13:46
@jwage another example on why conditional deprecations are just weird: https://github.com/doctrine/doctrine2/pull/6728#pullrequestreview-145655715

**Comment by Majkl578** [comment] 2018-08-13 17:38
> Looking at install statistics from packages, this is a no-contest that ends in a victory by default for the phpunit-bridge.

This is obviously not objective - phpunit-bridge is installed by default in all Symfony apps (even with Flex and symfony/website-skeleton) while phpstan-deprecations-rules is only ~one month old and not a dependency of a stack like Symfony.

**Comment by Ocramius** [comment] 2018-08-14 08:41
> Hello, it would be great to move this discussion to the FIG.

As much as I'd like a standardised way to do things, we first need one that works for us (@doctrine/doctrinecore, not Symfony nor anybody else), and that we can then propose as standard **AFTER** having it battle-tested.

The current `trigger_error()` and `@trigger_error()` is not working, hence we are discussing how to move forward.

Responding to @alcaeus'  https://github.com/doctrine/doctrine-website/issues/200#issuecomment-412534189

 > Using `trigger_error` solves this issue, but it's noisy: unless people have properly configured their runtime, deprecations will be logged which is undesired. While I don't think it would be a performance issue in a properly configured environment, these calls are always made, even in a production environment where most likely nobody is listening for them. The reason why the solution is normally to use `@trigger_error` is to make deprecations opt-in: without it, people will have to (possibly) update their PHP configuration to not receive these warnings, while using error suppression requires users to use some logger to catch these deprecation messages and handle them.

The problem is that `set_error_handler()` by default catches deprecations too: I had a customer that got a huge Sentry (an error reporting tool) bill because of a symfony upgrade that then triggered a few million of these errors, and also led to a massive slow-down of the infrastructure due to the added I/O. This led to a revert of the upgrade and some added work to simply suppress `E_USER_DEPRECATED`. They effectively won't know when something is deprecated, because they don't see it anymore anyway, and can't enable this sort of error reporting anyway.

`trigger_error()` affects everyone that has ever used `set_error_handler()` [anywhere in their codebase](https://3v4l.org/dl0R9), and is therefore not a viable tool IMO:

```php
<?php

set_error_handler('var_dump');

trigger_error('potato', E_USER_DEPRECATED);
@trigger_error('potato', E_USER_DEPRECATED);
```

 > Moving from the choices for announcing deprecations to the possibilities of handling them: for `@deprecated` there's [`phpstan/phpstan-deprecation-rules`](https://packagist.org/packages/phpstan/phpstan-deprecation-rules), for `@trigger_error` there's [`symfony/phpunit-bridge`](https://packagist.org/packages/symfony/phpunit-bridge). Looking at install statistics from packages, this is a no-contest that ends in a victory by default for the phpunit-bridge.

There's one massive advantage of `phpstan/phpstan-deprecation-rules` and `@deprecated`: deprecations are only for top-level dependencies.

That means that we'd get failures only if we *directly* rely on deprecated third-party API, while components in `vendor/` that do still rely on deprecated API are not considered as a failure.

This is massive, because otherwise any combination of deprecations in a vendor nested 10 level deep in a call graph can completely ruin the day, even if the maintainers of the top-level dependency already planned a migration. Without this sort of "shallow checking", every tiny change anywhere results in very complex dependency upgrade scenarios in order to keep things manageable, much like @doctrine/team-coding-standards discovered, when we had to lock down PHPCS *AND* `doctrine/coding-standard` via `composer.lock`.

 > On the other hand, triggering deprecations using @trigger_error() has been done for a while in Symfony and the tooling to support this is widespread and known to many users. While Doctrine is also used outside of the Symfony ecosystem, a large percentage of the install base comes from the Symfony framework and thus is familiar with the process of handling such deprecations in preparation for a major version upgrade.

Even if we'd be able to fix **our** issues by using `symfony/phpunit-bridge`, we (@doctrine/doctrinecore) only have this problem in the test suite, while downstream users have the problem with runtime code, not just PHPUnit. There's more than PHPUnit:

 * Behat
 * PHPSpec
 * Codeception
 * Your home-grown horror test setup
 * Your production server, tested by your customers that get a 500 error :-P

If we start adding the `@trigger_error()` semantic, we need to think about more than just failing downstream test suites, and hence a no-op such as `@deprecated`, whilst "a bit too silent" is probably best for everyone's mental health.

 > I would recommend using both methods for announcing deprecations (`@deprecated` and `@trigger_error()` while at the same time improving the tooling for static handling of deprecations and working together with others on a common way to handle deprecations.

I'd probably go with the "softer" one (`@deprecated`) for everything at this point: static analysis tooling picks it up. We can also make a one-liner that people use to download the static analysis tools for a one-off run (probably to be proposed directly to @phpstan) with our recommended settings.

Responding to @ostrolucky's https://github.com/doctrine/doctrine-website/issues/200#issuecomment-412279700:

 > We swap one thing with limitations with another thing with other limitations, instead of combining powers of both of them. I think everybody here realizes static analysis in its current state completely fails for any dynamic usage of deprecated code. I'm going to use painfully simple obvious example `new $_GET['foo']()`. There is no way any static analysis solution would catch that, but runtime solution will. Less painful examples are XML/YAML configuration of mapping and DIC. Same for twig extensions in where PHP code is in vendor. Why would we take away ability to detect these?

Yes, static analysis has limits, especially in a language like PHP, but that's something that tooling should kinda keep its hands off anyway. We can make things as easy as possible as we can for consumers, but anytime dynamic values occur, you are indeed on your own.

I can also tell you with confidence that users making things magic to that level often don't bother to write an integration test anyway, so they'll never know anyway :D

Deprecations outside the PHP language (YML/XML/etc) should probably be discussed elsewhere, but the best we could do is writing dedicated tooling instead. Much like PHP itself promoted static analysis tools for the PHP 5 to PHP 7 migration, so can we do as well by diffing our XSDs.

**Comment by ondrejmirtes** [comment] 2018-08-14 08:46
Nice summary!

> We can also make a one-liner that people use to download the static analysis tools for a one-off run

You can definitely configure PHPStan to just run the deprecation rules 😊

**Comment by ondrejmirtes** [comment] 2018-08-14 08:49
> Deprecations outside the PHP language (YML/XML/etc) should probably be discussed elsewhere, but the best we could do is writing dedicated tooling instead.

We discussed with @lcobucci that PHPStan could read entity metadata to also discover these deprecations although that would require a new set of rules. Would be a nice part of `phpstan-doctrine` though.

**Closed** 2018-09-10 20:55 UTC
Labels: Enhancement, Help Wanted, Question
