### ISSUE TITLE
Icons don't load in Firefox

### ISSUE THREAD

**Issue by stof** [doctrine/doctrine-website#504] opened 2023-08-23 14:39 UTC
Firefox validates the font files before loading them. And the icon font files gets rejected by the sanitizer (using Firefox 117.0 on Ubuntu)

**Comment by greg0ire** [comment] 2023-08-23 14:55
Duplicate of #502 

The fix is being deployed as we speak.

**Comment by greg0ire** [comment] 2023-08-23 14:56
Progress can be followed at https://github.com/doctrine/doctrine-website-build-prod/actions/runs/5952987337

**Closed by greg0ire** 2023-08-23 14:55 UTC

**Comment by greg0ire** [comment] 2023-08-23 14:58
Fixed :)
