### ISSUE TITLE
Wrong link target to expressions page

### ISSUE THREAD

**Issue by ondrejmirtes** [doctrine/doctrine-website#191] opened 2018-07-30 08:45 UTC
Hi,
I'm here https://www.doctrine-project.org/projects/doctrine-collections/en/latest/index.html and I'm trying to click on `You can read more about expressions >here<.` below the `matching` method description. Nothing happens.

I'm on Safari 11.1.2 on macOS 10.13.6.

**Comment by Ocramius** [comment] 2018-07-30 08:46
Can this be reproduced in a "contemporary" browser? :D

**Comment by ondrejmirtes** [comment] 2018-07-30 08:58
Yeah, it does the same thing in Chrome :P

**Comment by Ocramius** [comment] 2018-07-30 09:05
Thanks :+1:

**Comment by SenseException** [comment] 2018-08-03 20:17
Because the part of the `matching()` method had to be fixed anyway, I also did a fix for the link in PR doctrine/collections#158.

**Comment by SenseException** [comment] 2018-08-04 09:35
The changes got merged and the link now references to the Expressions page. Thank you for reporting this.

**Closed by SenseException** 2018-08-04 09:35 UTC
Labels: bug
