### ISSUE TITLE
Doctrine Mongo ODM search not working anymore

### ISSUE THREAD

**Issue by etshy** [doctrine/doctrine-website#328] opened 2019-10-31 12:47 UTC
I noticed today the search engine doesn't work anymore when you select the versions 2.0 and 1.3.2 for the bundle (results are always empty)
Surprisingly it works when you select the version 2.1 (upcoming). i didn't try with unmaintained versions.

Some screenshot to show the problem

V2.1
![](https://i.imgur.com/qHR3MRG.png)

V2.0
![](https://i.imgur.com/zv2pNoZ.png)

**Comment by SenseException** [comment] 2019-11-13 20:45
I can't reproduce the missing results when I locally build my search results for ODM, which makes debugging harder. Other project's search results are also affected.

**Comment by SenseException** [comment] 2023-11-03 20:18
This was fixed with a reoccurring index build of #420.

**Closed by SenseException** 2023-11-03 20:18 UTC
Labels: Bug
