### ISSUE TITLE
Merged Column Rendering

### ISSUE THREAD

**Issue by matt-usurp** [doctrine/doctrine-website#192] opened 2018-08-02 10:50 UTC
Unsure if this is a refactor that needs to happen on the syntax used in the documentation file or a change that needs to happen against the website rendering.

It looks like the rendering of merged columns isn't working as expected. For example of the DBAL documentation under the types reference the mapping table shows a load of `-+` characters. Viewing the RST directly in Github does render merged columns as expected so I am guessing its a rendering issue.

https://github.com/doctrine/dbal/blob/master/docs/en/reference/types.rst
https://www.doctrine-project.org/projects/doctrine-dbal/en/2.7/reference/types.html#mapping-matrix

**Comment by SenseException** [comment] 2018-08-02 13:47
Yes, this is an already know issue (#47). Still, thank you for taking your time to report this.

I'm closing this issue because it is a duplicate of #47

**Closed by SenseException** 2018-08-02 13:47 UTC
